-- Customize how diagnostics are displayed
-- vim.diagnostic.config({
--   virtual_text = {
--     prefix = require("utils.icons").prelude.bell,
--     source = true,
--     virt_text_pos = "eol",
--   },
--   float = {
--     source = true,
--   },
--   signs = true,
--   underline = true,
--   update_in_insert = true,
--   severity_sort = true,
-- })
