#!/usr/bin/env bash

# Keyboard shortcuts
set -g prefix C-x
unbind-key C-b

# Split window vertical
bind h split-window -h

# Split window horizontal
bind v split-window -v

bind-key r source-file ~/.config/tmux/tmux.conf

set -g escape-time 1

set -g base-index 1
set -g pane-base-index 1

set -g renumber-windows on

set -g default-terminal 'screen-256color'
set -g terminal-overrides ',xterm-256color:Tc'
