gui:
  mouseEvents: false
  nerdFontsVersion: "3"
theme:
  activeBorderColor:
    - '#1e66f5'
    - bold
  inactiveBorderColor:
    - '#6c6f85'
  optionsTextColor:
    - '#1e66f5'
  selectedLineBgColor:
    - '#ccd0da'
  cherryPickedCommitBgColor:
    - '#bcc0cc'
  cherryPickedCommitFgColor:
    - '#1e66f5'
  unstagedChangesColor:
    - '#d20f39'
  defaultFgColor:
    - '#4c4f69'
  searchingActiveBorderColor:
    - '#df8e1d'

authorColors:
  '*': '#7287fd'
  commitLength:
    show: true
  showRandomTip: false
  showIcons: true
  showFileIcons: true
  border: single
git:
  mainBranches:
    - master
    - main
    - develop
  parseEmoji: true
