gui:
  mouseEvents: false
  nerdFontsVersion: ""
  commitLength:
    show: true
  showRandomTip: false
  showIcons: false
  showFileIcons: false
  border: single
git:
  mainBranches:
    - master
    - main
    - develop
  parseEmoji: true
