[tools]
"cargo:bat" = "latest"
"cargo:du-dust" = "latest"
"cargo:fd-find" = "latest"
"cargo:git-delta" = "latest"
"cargo:gitui" = "latest"
"cargo:lsd" = "latest"
"cargo:ripgrep" = "latest"
"cargo:starship" = "latest"
"cargo:tree-sitter-cli" = "latest"
"cargo:uv" = "latest"
"github:cli/cli" = "latest"
"github:neovim/neovim" = "latest"
go = "latest"
"go:github.com/jesseduffield/lazygit" = "latest"
node = "lts"
"pypi:yt-dlp" = "latest"
python = "latest"
rust = "latest"
usage = "latest"
