local snippet = require("snippets.utils").snippet

return {
  snippet("columns-1", "columns: 1;"),
  snippet("columns-2", "columns: 2;"),
  snippet("columns-3", "columns: 3;"),
  snippet("columns-4", "columns: 4;"),
  snippet("columns-5", "columns: 5;"),
  snippet("columns-6", "columns: 6;"),
  snippet("columns-7", "columns: 7;"),
  snippet("columns-8", "columns: 8;"),
  snippet("columns-9", "columns: 9;"),
  snippet("columns-10", "columns: 10;"),
  snippet("columns-11", "columns: 11;"),
  snippet("columns-12", "columns: 12;"),
  snippet("columns-auto", "columns: auto;"),
  snippet("columns-3xs", "columns: 16rem;"),
  snippet("columns-2xs", "columns: 18rem;"),
  snippet("columns-xs", "columns: 20rem;"),
  snippet("columns-sm", "columns: 24rem;"),
  snippet("columns-md", "columns: 28rem;"),
  snippet("columns-lg", "columns: 32rem;"),
  snippet("columns-xl", "columns: 36rem;"),
  snippet("columns-2xl", "columns: 42rem;"),
  snippet("columns-3xl", "columns: 48rem;"),
  snippet("columns-4xl", "columns: 56rem;"),
  snippet("columns-5xl", "columns: 64rem;"),
  snippet("columns-6xl", "columns: 72rem;"),
  snippet("columns-7xl", "columns: 80rem;"),
}
